### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by GeekYW** [SongJiaqiang/EvoRadio#1]
soundQueue?.playAtSecond(second)这句一直报错

**Comment by SongJiaqiang** [comment]
这里的确有个问题，这是从AFSoundManager库中带出的，这个库并没有实现这个方法。如果你看过代码的话，会发现我已经在SoundQueues.swift这个扩展类文件中做了相应的说明。
临时解决方法只能修改AFSoundManager库，在AFSoundQueue类中添加如下代码：
`-(void)playAtSecond:(NSInteger)second {
    [_queuePlayer playAtSecond:second];
}`
- 这个Bug其实很早就有人提出来了，但是AFSoundMnanager的作者一直没有回应，看他们的commit也有发现，他们已经1年没更新了。我现在正准备使用其他音频库替换这个。

**Comment by GeekYW** [comment]
恩恩， 好的
