### ISSUE TITLE
pod之后一直编译不通过

### ISSUE THREAD

**Issue by dongdong3344** [SongJiaqiang/EvoRadio#4]
failed to emit precompiled header '/var/folders/kd/4gh0_kxx3jx4thjb_sssmmcw0000gn/T/EvoRadio-Bridging-Header-3e5215.pch' for bridging header '/Users/ringo/Downloads/EvoRadio-master/EvoRadio/Resources/EvoRadio-Bridging-Header.h'

**Comment by SongJiaqiang** [comment]
首先，这个error和pod没有关系。
根据你的错误信息，可能是最近更新了bridging文件导致的，你可以先clean（shift+command+K）一下再编译试试。

**Comment by dongdong3344** [comment]
还是不行，clean 很多次了，一直是这个提示。另外移出pod管理库后，我自己pod之后，编译时还是提示错误。

**Comment by dongdong3344** [comment]
我大概知道原因了，有问题再请教你。
