### ISSUE TITLE
请求下ObjcLevelDB 如何使用？

### ISSUE THREAD

**Issue by dongdong3344** [SongJiaqiang/EvoRadio#6]
我build时，提示ObjcLevelDB Module不存在，于是我在gitHub上找到了你上传的那个文件，但是copy到工程里，clean后再build，还是提示不存在。

**Comment by dongdong3344** [comment]
原来是导入 import Objective_LevelDB

**Comment by SongJiaqiang** [comment]
我已经将所有第三方库迁移到了[Carthage](https://github.com/Carthage/Carthage)，clone项目之后请使用`carthage update`命令安装，老项目请切换到[pod](https://github.com/SongJiaqiang/EvoRadio/tree/pod)分支。

**Comment by dongdong3344** [comment]
你能不能把pod之后的完整项目传一下？我看了下没有到100M，我下了你的工程，然后重新pod了三方库，编译后提示Apple Mach-O Linker Error Group：clang: error: linker command failed with exit code 1 (use -v to see invocation)
查了很久也没有查到原因。你说的Carthage，我还没有使用过。直接是cd /文件目录，然后 使用carthage update 命令吗 ？谢谢。

**Comment by dongdong3344** [comment]
已经搞定了。
